name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug 
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce the bug?
      description: Steps to reproduce the behavior
      placeholder: Tell us what you see!
      value: "
        1. Go to '...' /n
        2. Click on '....' /n
        3. Scroll down to '....' /n
        4. See error
       "
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes: 
        label: Screenshots
        description:  If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: browser
    attributes:
      label: Browser
      description: Please specify browser information
      placeholder: Which browser are you using?
      value: "
         - Operating System [e.g IOS] \n
         - Browser [e.g chrome, safari] \n
         - Version [e.g 22]
       "
    validations:
      required: true
  - type: textarea
    id: smartphone
    attributes:
      label: Smartphone
      description: Please specify device information
      placeholder: Which device are you using?
      value: "
         - Device [e.g. iPhone6] \n
         - OS [e.g. iOS8.1] \n
         - Browser [e.g. stock browser, safari] \n
         - Version [e.g 22]
       "
    validations:
      required: true   
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context 
      description: Add any other context about the problem here.
      placeholder: Which device are you using?
    validations:
      required: false
