name: Add issues to project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: macos-latest
    steps:
      - uses: actions/add-to-project@0.3.0
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/carinaluise/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
